### ISSUE TITLE
can fisheye be used for calibration?

### ISSUE THREAD

**Issue by crankler** [ram-lab/plycal#2]
hi, we try to use realsense T265 and VLP16 and use your method for calibrtation, but the calibration result can't suit in picture.
First, we ues the intrinsic parameters of the t265 api to undistort the camera and we want to use it as a common camera, then we follow your instrutment to calibration, but the result as follow:
![rrr](https://user-images.githubusercontent.com/31907141/82626369-32961200-9c1a-11ea-9f5b-5aed98f86917.png)
Then we use the t265 api as the config parameters, but the result also is worse.
So can we use this method?

**Comment by neophack** [comment]
https://github.com/ram-lab/plycal/blob/82a4cd0e53685ce41d5e09aeb733204d6072fd91/PlyCal_qt/data_reader.cpp#L135
you can change undistort use
```  c++
  if (useFisheye_){
        cv::Mat D;
        D_.copyTo(D);
        D.pop_back();
        cv::Matx33d newK = K_;
        cv::fisheye::undistortImage(img_orig, *img, K_, D,newK);
    }else{
        cv::undistort(img_orig, *img, K_, D_);
    }
```

**Comment by liaoqinghai** [comment]
Thanks @neophack  
@crankler please change the camera model.

**Comment by arjunskumar** [comment]
@crankler how do you calibrate the intrinsic params of the camera?
