### ISSUE TITLE
在加载config提示段错误

### ISSUE THREAD

**Issue by ltshadow** [ram-lab/plycal#3]
老师你好，我在跑这个项目的时候，编译完成后运行PlyCal-qt加载config时闪退并提示段错误，如下
width: 378.553 length: 469.008
 angle_width: 103.683 angle_length: 17.9155
段错误 (核心已转储)
我想请问下老师你遇到过这个问题吗？或者这个问题可能是因为什么造成的？谢谢老师

**Comment by liaoqinghai** [comment]
是不是json配置修改后不合法了？
