### ISSUE TITLE
/usr/bin/ld: cannot find -lQt5::Widgets

### ISSUE THREAD

**Issue by Deephome** [ram-lab/plycal#5]
Thank you for your great work! During compilation, I encountered the following problem:

[100%] Linking CXX executable PlyCal-qt
/usr/bin/ld: cannot find -lQt5::Widgets
collect2: error: ld returned 1 exit status
make[2]: *** [PlyCal_qt/CMakeFiles/PlyCal-qt.dir/build.make:500: PlyCal_qt/PlyCal-qt] Error 1
make[1]: *** [CMakeFiles/Makefile2:117: PlyCal_qt/CMakeFiles/PlyCal-qt.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

I have installed qt5 by apt-get or .run. But the issue cannot be fixed. what you mean about qt5 (system) in readme.md ?

**Comment by liaoqinghai** [comment]
May I know the Ubuntu version you tested?  
I tested with Ubuntu 16.04 and it should also work with later version. Qt5 (system) means the built-in qt library of shipped  with Ubuntu. For Ubuntu 16.04, the default Qt5 version is 5.5.1
 For Qt and Cmake, I follow the : https://doc.qt.io/qt-5/cmake-manual.html

**Comment by Deephome** [comment]
@liaoqinghai 
Thank you for your reply. I use Ubuntu 20.04 for which the default Qt5 version is 5.12.8. In addition, I used VTK7, how about the VTK version you used? I suspect this issue is caused by VTK accoding to the following links:
[https://bugs.archlinux.org/task/43007](https://bugs.archlinux.org/task/43007)
[https://forum.freecadweb.org/viewtopic.php?t=15646](https://forum.freecadweb.org/viewtopic.php?t=15646)

**Comment by liaoqinghai** [comment]
I adjust the cmakelist.txt and try with Ubuntu 20.04, now I can compile successfully. But it seems there is runtime problem with the GUI program.

**Comment by Deephome** [comment]
> I adjust the cmakelist.txt and try with Ubuntu 20.04, now I can compile successfully. But it seems there is runtime problem with the GUI program.
Hi, have you solved this problem?

**Comment by TongShuo-Demon** [comment]
2024.12.12我放弃了
